apiVersion: v1
data:
  prometheus-additional.yaml: |
    - job_name: 'worker-metrics'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: worker

    - job_name: 'api-metrics'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: api
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus-additional.yaml":"- job_name: 'worker-metrics'\n  kubernetes_sd_configs:\n  - role: pod\n  relabel_configs:\n  - source_labels: [__meta_kubernetes_pod_label_app]\n    action: keep\n    regex: worker\n\n- job_name: 'api-metrics'\n  kubernetes_sd_configs:\n  - role: pod\n  relabel_configs:\n  - source_labels: [__meta_kubernetes_pod_label_app]\n    action: keep\n    regex: api\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"additional-scrape-configs","namespace":"monitoring"}}
  creationTimestamp: "2025-11-25T16:36:53Z"
  name: additional-scrape-configs
  namespace: monitoring
  resourceVersion: "55507"
  uid: c4f6397b-382c-4f8f-a663-6ccdf743a58a
