apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1
  kind: Kafka
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kafka.strimzi.io/v1","kind":"Kafka","metadata":{"annotations":{},"name":"my-cluster","namespace":"kafka"},"spec":{"entityOperator":{"topicOperator":{},"userOperator":{}},"kafka":{"config":{"default.replication.factor":1,"min.insync.replicas":1,"offsets.topic.replication.factor":1,"transaction.state.log.min.isr":1,"transaction.state.log.replication.factor":1},"listeners":[{"name":"plain","port":9092,"tls":false,"type":"internal"}],"metadataVersion":"4.1-IV1","version":"4.1.1"}}}
    creationTimestamp: "2025-11-25T03:08:13Z"
    generation: 1
    name: my-cluster
    namespace: kafka
    resourceVersion: "13876"
    uid: da66eaab-aced-4e93-abba-239e80b1ea7f
  spec:
    entityOperator:
      topicOperator: {}
      userOperator: {}
    kafka:
      config:
        default.replication.factor: 1
        min.insync.replicas: 1
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      metadataVersion: 4.1-IV1
      version: 4.1.1
  status:
    clusterId: eyd64ECtSvKyZLiJfgam-g
    conditions:
    - lastTransitionTime: "2025-11-25T03:08:30.949555254Z"
      message: A Kafka cluster with a single broker node and ephemeral storage will
        lose topic messages after any restart or rolling update.
      reason: KafkaStorage
      status: "True"
      type: Warning
    - lastTransitionTime: "2025-11-25T03:08:30.949588129Z"
      message: A Kafka cluster with a single controller node and ephemeral storage
        will lose data after any restart or rolling update.
      reason: KafkaStorage
      status: "True"
      type: Warning
    - lastTransitionTime: "2025-11-25T03:09:16.665411595Z"
      status: "True"
      type: Ready
    kafkaMetadataVersion: 4.1-IV1
    kafkaNodePools:
    - name: dual-role
    kafkaVersion: 4.1.1
    listeners:
    - addresses:
      - host: my-cluster-kafka-bootstrap.kafka.svc
        port: 9092
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9092
      name: plain
    observedGeneration: 1
    operatorLastSuccessfulVersion: 0.49.0
kind: List
metadata:
  resourceVersion: ""
apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1
  kind: KafkaNodePool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kafka.strimzi.io/v1","kind":"KafkaNodePool","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"my-cluster"},"name":"dual-role","namespace":"kafka"},"spec":{"replicas":1,"roles":["controller","broker"],"storage":{"kraftMetadata":"shared","type":"ephemeral"}}}
    creationTimestamp: "2025-11-25T03:06:25Z"
    generation: 1
    labels:
      strimzi.io/cluster: my-cluster
    name: dual-role
    namespace: kafka
    resourceVersion: "13691"
    uid: 6fc24600-fa3c-4d4b-9319-ab8cc729029d
  spec:
    replicas: 1
    roles:
    - controller
    - broker
    storage:
      kraftMetadata: shared
      type: ephemeral
  status:
    clusterId: eyd64ECtSvKyZLiJfgam-g
    conditions: []
    labelSelector: strimzi.io/cluster=my-cluster,strimzi.io/name=my-cluster-kafka,strimzi.io/kind=Kafka,strimzi.io/pool-name=dual-role
    nodeIds:
    - 0
    observedGeneration: 1
    replicas: 1
    roles:
    - controller
    - broker
kind: List
metadata:
  resourceVersion: ""
apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1
  kind: KafkaTopic
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kafka.strimzi.io/v1","kind":"KafkaTopic","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"my-cluster"},"name":"jobs","namespace":"kafka"},"spec":{"partitions":1,"replicas":1}}
    creationTimestamp: "2025-11-25T02:22:50Z"
    finalizers:
    - strimzi.io/topic-operator
    generation: 1
    labels:
      strimzi.io/cluster: my-cluster
    name: jobs
    namespace: kafka
    resourceVersion: "13806"
    uid: a7247dd3-e9f0-41f3-aaad-754f13420b31
  spec:
    partitions: 1
    replicas: 1
  status:
    conditions:
    - lastTransitionTime: "2025-11-25T03:08:56.519089710Z"
      status: "True"
      type: Ready
    observedGeneration: 1
    topicId: uw456HBoQlGqFPnAZ5Fghw
    topicName: jobs
kind: List
metadata:
  resourceVersion: ""
