apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis","namespace":"default"},"spec":{"ports":[{"name":"redis","port":6379,"targetPort":6379}],"selector":{"app":"redis"},"type":"ClusterIP"}}
  creationTimestamp: "2025-11-25T01:00:06Z"
  name: redis
  namespace: default
  resourceVersion: "467"
  uid: 137c4a33-38a1-44a4-9f08-69475f9d6773
spec:
  clusterIP: 10.96.194.167
  clusterIPs:
  - 10.96.194.167
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
