apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1
  kind: KafkaNodePool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kafka.strimzi.io/v1","kind":"KafkaNodePool","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"my-cluster"},"name":"dual-role","namespace":"kafka"},"spec":{"replicas":1,"roles":["controller","broker"],"storage":{"kraftMetadata":"shared","type":"ephemeral"}}}
    creationTimestamp: "2025-11-25T03:06:25Z"
    generation: 1
    labels:
      strimzi.io/cluster: my-cluster
    name: dual-role
    namespace: kafka
    resourceVersion: "13691"
    uid: 6fc24600-fa3c-4d4b-9319-ab8cc729029d
  spec:
    replicas: 1
    roles:
    - controller
    - broker
    storage:
      kraftMetadata: shared
      type: ephemeral
  status:
    clusterId: eyd64ECtSvKyZLiJfgam-g
    conditions: []
    labelSelector: strimzi.io/cluster=my-cluster,strimzi.io/name=my-cluster-kafka,strimzi.io/kind=Kafka,strimzi.io/pool-name=dual-role
    nodeIds:
    - 0
    observedGeneration: 1
    replicas: 1
    roles:
    - controller
    - broker
kind: List
metadata:
  resourceVersion: ""
